# Generated by Django 5.1.5 on 2025-02-12 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemDeServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='codigo',
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='bairro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='ocorrencia.bairro'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='data_solicitacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='ocorrencia.datasolicitacao'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='parecer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='ocorrencia.parecer'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='situacao_agua_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='ocorrencia.situacaoaguacliente'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='matricula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='ocorrencia.matricula'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='ordem_de_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='ocorrencia.ordemdeservico'),
        ),
    ]
