# Generated by Django 5.1.5 on 2025-02-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0002_matricula_ordemdeservico_remove_ocorrencia_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='ordem_de_servico',
            field=models.TextField(blank=True, null=True),
        ),
    ]
