# Generated by Django 5.1.5 on 2025-02-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0003_alter_ocorrencia_ordem_de_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_solicitacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='ordem_de_servico',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
