# Generated by Django 5.1.5 on 2025-02-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0004_alter_ocorrencia_data_solicitacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='matricula',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
