# Generated by Django 5.1.5 on 2025-03-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0005_plantao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantao',
            options={'verbose_name': 'Plantão', 'verbose_name_plural': 'Plantões'},
        ),
        migrations.AlterField(
            model_name='plantao',
            name='inicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
