# Generated by Django 5.1.5 on 2025-02-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0006_alter_ocorrencia_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='matricula',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='ordem_de_servico',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
