# Generated by Django 5.1.5 on 2025-03-30 18:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0006_alter_plantao_options_alter_plantao_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantao',
            name='inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
