# Generated by Django 5.1.5 on 2025-03-30 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0007_alter_plantao_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='plantao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='ocorrencia.plantao', verbose_name='Plantao'),
        ),
    ]
