# Generated by Django 5.1.5 on 2025-02-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0008_alter_ocorrencia_ordem_de_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='ordem_de_servico',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
