# Generated by Django 5.1.5 on 2025-03-13 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0010_statusregiao_ocorrencia_status_regiao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataSolicitacao',
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='parecer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='situacao_agua_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='status_regiao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='bairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='ocorrencia.bairro'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_solicitacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='descricao',
            field=models.TextField(),
        ),
       migrations.AlterField(
            model_name='ocorrencia',
            name='matricula',
            field=models.IntegerField(default=0),  
        ),

        migrations.AlterField(
            model_name='ocorrencia',
            name='ordem_de_servico',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Parecer',
        ),
        migrations.DeleteModel(
            name='SituacaoAguaCliente',
        ),
        migrations.DeleteModel(
            name='StatusRegiao',
        ),
    ]
