# Generated by Django 5.1.5 on 2025-03-25 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0011_delete_datasolicitacao_alter_ocorrencia_parecer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Parecer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SituacaoAguaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatusRegiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='matricula',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='parecer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='ocorrencia.parecer'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='situacao_agua_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='ocorrencia.situacaoaguacliente'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='status_regiao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='ocorrencia.statusregiao'),
        ),
    ]
