# Generated by Django 5.1.5 on 2025-03-26 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0012_datasolicitacao_parecer_situacaoaguacliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='status_ocorrencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='ocorrencia.statusocorrencia'),
        ),
    ]
