# Generated by Django 5.1.5 on 2025-03-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0013_statusocorrencia_ocorrencia_status_ocorrencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocorrencia',
            old_name='status_ocorrencia',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_solicitacao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
